[package]
name = "mtk_uartboot"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-only"

[profile.release]
panic = "abort"
strip = true

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
clap-num = "1.0.2"
serialport = { version = "4.3", default-features = false }
