[package]
name = "mtk_uartboot"
version = "0.1.0"
edition = "2021"
license = "GPL-2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
clap-num = "1.0.2"
serialport = "4.3.0"
